### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by pmfx** [mnoskov/pagebuilder#1]
It would be great to see readme/documentation translated to english.

**Comment by fourroses666** [comment]
We can help. And if you can add the text multilang placeholders that will be great too :)

So if you can add an lang folder with the translation that will be great.
Translation for text in the `.tpl` etc.:
`<option value="">-- Выберите тип блока --</option>`

**Comment by mnoskov** [comment]
Good, but I think, it's not problem to translate interface. Help needed with documentation

**Comment by mnoskov** [comment]
https://github.com/sunhaim/contentblocks/commit/71e11e5793ce77ccb96a21fa7b53b21188501852

**Comment by fourroses666** [comment]
Hi Sunhaim, I'm having trouble with making a good Pull request. 
Don't know what I'm doing wrong.

Maybe you can grab the readme.md and nederlands-utf8.php files from here:
https://github.com/sunhaim/contentblocks/pull/2/commits/3fb908cb73e532212e2d2b7ea23b4c8f3767edc2

**Comment by mnoskov** [comment]
Ok
