### ISSUE TITLE
Need snippet parameter for set document-source of blocks

### ISSUE THREAD

**Issue by mnoskov** [mnoskov/pagebuilder#19]
Any other parameters?

**Comment by mnoskov** [comment]
&block - for filtering by block type,
&offset,
&limit

**Comment by fourroses666** [comment]
What do you think about my idea to add an option to use icons (or icons with text) for blocktypes?

&type=`dropdown` <-- default
&type=`icons`

Then in the config file you could select the icon for the block.
_font awesome or use custom icons (I can make)_

![cblocks](https://user-images.githubusercontent.com/523389/28111849-36d1b6d6-66f7-11e7-8222-11f423d54fe0.png)

Some ideas of others;
- http://createagreatwebsite.net/wp-content/uploads/2015/09/Squarespace-Content-Blocks.jpg
- http://docs.telerik.com/kendo-ui/styles-and-layout/icons-web#layout-and-navigation
- http://kb.mailchimp.com/binaries/content/gallery/mailchimpkb/common/campaigns/design-step/camp_cb_design_contentblocks.jpg
- https://docs.modmore.com/en/ContentBlocks/v1.x/Custom_Inputs/Icons.html


![inline-icon](https://user-images.githubusercontent.com/523389/28113189-e3718908-66fb-11e7-9af2-5309bd040741.jpg)

**Comment by mnoskov** [comment]
Great idea.
This option can be extended:
"dropdown",
"icons" - for use fontawesome icons, icon-class should be provided in config,
"images" - for use images.

**Comment by mnoskov** [comment]
a85706f

**Comment by fourroses666** [comment]
Next week I can make some default icons if you like

**Comment by mnoskov** [comment]
Thanks, but wait, first I add this functionality, for knowing, which icons needed

**Comment by mnoskov** [comment]
Hi, Marc!
Do you have any suggestions for icons?
This would be great start point - http://kb.mailchimp.com/binaries/content/gallery/mailchimpkb/common/campaigns/design-step/camp_cb_design_contentblocks.jpg

**Comment by fourroses666** [comment]
Hi, yes these look very nice. :)
That will be a good startingpoint. 
I'd like to have them look like these.

What do you want me to do? 
Do you use some placeholders and I replace these? 

_(I haven't upgraded CB yet and don't know how it looks now when using images)_

**Comment by mnoskov** [comment]
I'm planning to add sample configuration files for "text", "image", "images gallery", "image card", "image + description".
So it will be great, if you draw images for this blocks.
Max size 80x60

It will look like this:
<img src="https://monosnap.com/file/kMmR8ItGkVDuHlgbwnMQXXJBSdaOlX.png">

**Comment by fourroses666** [comment]
Oke, I will make these icons 160x120 (retina) and can be resized to the 80x60. Today a bit busy but tomorrow some time for it :)

Yea upgraded and see its already possible to select images / icons! Nice

**Comment by mnoskov** [comment]
I've created folder for you:
https://github.com/mnoskov/contentblocks/tree/master/assets/plugins/contentblocks/images

**Comment by fourroses666** [comment]
Oké!

**Comment by fourroses666** [comment]
Having no internet at the moment. There is an internet breakdown here on my zipcode and really need it. Probably back tomorrow..

**Comment by mnoskov** [comment]
There's no hurry :)

**Comment by fourroses666** [comment]
Hi, I have made some start on the icons;
[pb.zip](https://github.com/mnoskov/pagebuilder/files/1236297/pb.zip)

**Comment by mnoskov** [comment]
Cool icons!

**Comment by fourroses666** [comment]
I would like to make vectors of them (PS Illustrator) and do a small restyle but at the moment we can use these. 👍 👍

**Comment by fourroses666** [comment]
Also have to add some icons like "Map" and "List" and probably allot more.

**Comment by pmfx** [comment]
Cool icons indeed!

**Comment by mnoskov** [comment]
Excellent job, @fourroses666 

<img src="https://monosnap.com/file/2TLakj5pK1zGnrA77P5nb52PHlWH3J.png">

**Comment by fourroses666** [comment]
Don't know where else to ask.

I have set the plugin to images. But how can I show the icon?
Do I have to add the image/iconname in the configfile?

**Comment by mnoskov** [comment]
Yes, you must set it in config file
```
'image' => 'assets/plugins/pagebuilder/images/image.jpg',
```

**Comment by fourroses666** [comment]
👍
