### ISSUE TITLE
Test on newest development version

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#20]
I did a test on the latest development version (and updated ContentBlocks on the Extras)
Added a new config file and that showed up but somehow I can't remove or add blocks.

Debugger gave an issue on line 449 - interaction.js

_TypeError: conf is undefined_   :

_jQuery.Deferred exception: conf is undefined initializeRichField_

When removing the lowest block and saving the page its back again. (buggy)

**Comment by fourroses666** [comment]
Ah tested on a new page and there no issue with adding/removing..

Hmm don't know whats wrong on the old page.

**Comment by mnoskov** [comment]
Something with tinymce4 system settings...
