### ISSUE TITLE
Use chunk in config file (for showing multiple images)

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#23]
I tried to use a Chunk to show multiple images.
Would be great if that was possible.

```
        'templates' => [
            'owner' => '
                <div>Text:<br> [+text+]</div>
                <div>Images:<br> [+images+]</div>
            ',
            'images' => '
               {{testchunk}}
            '
```

Content of my testchunk Chunk:
`test: <img src="[+image+]"><br>`

Works;
```
            'images' => '
               test: <img src="[+image+]"><br>
            '
```

This don't work, text is visible but images are not:
```
            'images' => '
               {{testchunk}}
            '
```

_Also noticed I had to refresh the sitecache to show changes when updating the config file, don't know if thats normal behaviour._

**Comment by mnoskov** [comment]
Try this:
```
'images' => '@CHUNK testchunk'
```

**Comment by mnoskov** [comment]
As for sitecache, this is normal behaviour

**Comment by fourroses666** [comment]
Thanks, works great! Really like it.


******
My test;

```
<?php

return [
	'title' => 'Test',
	
	'templates' => [
		'owner' => '@CHUNK cb_owner',
		'images' => '@CHUNK cb_images'
	],
	
	'fields' => [
		'text' => [
			'caption' => 'Text',
			'type'    => 'text',
		],

		'images' => [
			'caption' => 'Images',
			'type'    => 'group',
			'fields'  => [
				'image' => [
					'caption' => 'Image',
					'type'    => 'image'   
				],
			],
		],
	],
];

```

Chunk cb_owner: `<div>Text: [+text+]</div><div>Images:<br> [+images+]</div>`
Chunk cb_images: `<img src="[+image+]" width="100" border="1" /><br>`

**Comment by fourroses666** [comment]
Re sitecache:

There are no cache "issues" when working with chunks.
Just when changing the config file it needs a "Clear Cache" so thats great  👍 👍
