### ISSUE TITLE
Select different block and then same again then the images are gone

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#25]
I use a custom Block (test), I can add text and multiple images.

When added the block en fill it with content and images, then select a different block (all fields) and then the original one again (test) the text is still there but the images are gone.

I don't know if this behaviour is correct. Maybe better; no block change possible after added or somehow remember the input of the images?

**Comment by mnoskov** [comment]
This is "ficha" :)

**Comment by mnoskov** [comment]
In other words, when you changing type of block, all fields that have same names and structure, will retain their values.
In your situation in block 'all_fields' no field 'images', so after changing type back this field empty

**Comment by fourroses666** [comment]
Yes, didn't expected it was empty after changing back.

If you like it, we can add an option to the config file?
An option so we are able to lock the "Select an other block for this block" ?

Just like the 'show_in_templates' => [ 3 ], 
but then 'lock_select_different_block' => [ 1 ]. _(default 0?)_

**Comment by mnoskov** [comment]
Maybe will be better to save all values through all changes of block type, instead of collecting values on each changig?

**Comment by fourroses666** [comment]
Yea I think so, if I understand what you are saying.

--> When saving the page the values are saved and then you won't loose the content of the original blockfields?

**Comment by mnoskov** [comment]
No, not saving, only changing type of block

**Comment by fourroses666** [comment]
Sounds good to me. No clients who are crying because they lost their content :P
