### ISSUE TITLE
Richtext don't work

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#27]
Any idea why its not working?

![richtext](https://user-images.githubusercontent.com/523389/27909965-60133702-6253-11e7-954f-178191bd6ef6.jpg)

**Comment by mnoskov** [comment]
Any error in console?

**Comment by fourroses666** [comment]
I see an error: TypeError: conf is undefined

jQuery.Deferred exception: conf is undefined initializeRichField@http://test.site.nl/assets/plugins/contentblocks/js/interaction.js?0.3.3:449:33

Don't know if thats the issue. (MODXRE2 and also with the Dropdown version)

```

 // save all standard options for other fields
                            for ( option in options ) {
449                          old[option] = conf[option] ? conf[option] : undefined;
                                conf[option] = options[option];
                            }
```

**Comment by fourroses666** [comment]
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Errors/Unexpected_type

**Comment by mnoskov** [comment]
TinyMCE4 installed?

**Comment by mnoskov** [comment]
Have you set option "theme" for richtext in config?

**Comment by fourroses666** [comment]
![tinymce](https://user-images.githubusercontent.com/523389/27910955-a46649ea-6257-11e7-94c4-eed460c648db.jpg)

**Comment by mnoskov** [comment]
No errors here, what about config file?

**Comment by fourroses666** [comment]
Shall I give you access to the testsite? If you don't mind. 

Could also be I use the development version 1.2.2-beta3

**Comment by mnoskov** [comment]
Can you send access to nm@perm-tools.ru?

**Comment by fourroses666** [comment]
Done, also seen my video? 
https://www.youtube.com/watch?v=PlAR4BFS3Lw&feature=youtu.be&hd=1

**Comment by mnoskov** [comment]
Yes, but have no idea, what's wrong. I will test it on your site little later.

**Comment by fourroses666** [comment]
No problem. (You can test on new pages and existing ones).
