### ISSUE TITLE
When adding / removing and shuffle blocks and saving then get some weird issues

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#28]
When I add a new page and add some blocks and save the page. Then shuffle and remove the blocks, delete and add blocks, then things go wrong.

I can give you acces to my testsite.

See video here:
https://www.youtube.com/watch?v=PlAR4BFS3Lw&feature=youtu.be&hd=1

**Comment by mnoskov** [comment]
This must be fixed too, can you check?

**Comment by fourroses666** [comment]
Yea looks like its fixed. If I notice issues again I will report :) Thx
