### ISSUE TITLE
Error with prefix

### ISSUE THREAD

**Issue by Dmi3yy** [mnoskov/pagebuilder#29]
Andrey Shin, [Jul 12, 2017, 4:35 PM]:
хм.. что-то странное с ContentBloks  Выдает ошибку:
Execution of a query to the database failed - Table 'az_admrl.modx_site_content' doesn't exist
SQL > SELECT id FROM modx_site_content WHERE alias = "sitemap.xml" LIMIT 1;
Почему-то плагин решил, что префикс таблцы modx_

и зачем ему sitemap

**Comment by mnoskov** [comment]
В примерах есть такой вызов
https://github.com/sunhaim/contentblocks/blob/master/assets/plugins/contentblocks/config/all_fields.php#L38

**Comment by Shin777** [comment]
Спасибо! Чтобы  такой путаницы не было, хорошо бы примеры в другую папку кинуть. Типа sample-config/

**Comment by Dmi3yy** [comment]
Кстати да правильна мысль ибо без настройки все равно не используется а при обновлении на живом проекте сейчас приходиться удалять файлики или они вылазят у менеджера

**Comment by Shin777** [comment]
Еще в доках прописать хорошо бы, что файла конфига достаточно и никакого TV,  как в MultyTV делать не нужно.

**Comment by mnoskov** [comment]
d4ade85 2c1e0f7
