### ISSUE TITLE
Project name?

### ISSUE THREAD

**Issue by Mark-H** [mnoskov/pagebuilder#35]
Hello! Great work on this plugin. I took a quick look through the video linked in the readme, and it looks like a potential game changer for Evo. While I haven't touched Evolution in ages, it's good to see cool stuff being invented for it still. I wish you all the best with the project.

I'm just a bit worried about the name though. As you might be aware, modmore launched an extra also called [ContentBlocks](https://www.modmore.com/contentblocks/) back in 2014. That extra is for MODX Revolution.

Given that it only happened very recently that Evo officially dropped "MODX" from the name, and people are still used to calling it "MODX evo" (e.g. [this tweet](https://twitter.com/pmfx/status/893203497759506432) included the #modx hashtag before evo), I'm worried people may get confused about this extra. Searching for "modx contentblocks" for example, might return both the modmore and this one. That's not good for anyone.

The same name could also be interpreted as it is supported by modmore, or a direct clone/fork aimed at Evolution. Neither of those two things is true, leading to more potential confusion.

I'd appreciate it if you would think about a new name for your project. Given the project is still fairly new, a name change now would be a lot easier than it would be a few years down the road when (hopefully) you have lots of people using it. 

Thanks!

**Comment by pmfx** [comment]
ContentBlocks phrase is rather common, but I see why you're concerned and that it may be confusing for some. @mnoskov if you are going to change project name then I would suggest "**EvoBlocks**".

**Comment by mnoskov** [comment]
I agree, that name is common, so I dont know what to say yet.

**Comment by Mark-H** [comment]
Sure, there are other systems for other CMSes named the same. I'm fairly sure there weren't any with the exact same name when the modmore one came out - but can be wrong, it's been a while.

The problem is evo and revo are a lot easier to get mixed up, compared to for example sitefinity and MODX. Someone posting on a sitefinity forum is obviously talking about that one, while on the MODX forum they could be talking about either yours or mine. 

I like the name EvoBlocks :)

**Comment by pmfx** [comment]
Some suggestions:

- EvoBlocks
- ContentChunks (that can be confusing)
- ContentPieces
- ContentParts
- LayoutBlocks
- EvoFragments
- EvoParagraphs
- EvoParts

**Comment by fourroses666** [comment]
EvoBlocks, LayoutBlocks or PageBuilder sounds best, but if you ask me;
I don't really see any problems to keep the name ContentBlocks.
WP (2011) and MailChimp are also using it because its just the best name for it.
The brandname MODX will be / is already removed.

**Comment by Mark-H** [comment]
MODX being removed from the evo brand does not instantly remove Evo from the MODX ecosystem. People are still talking about Evo in the MODX-branded forums, slack, and using the #modx hashtag on twitter when they're talking about Evo CMS.

People are not talking in those places about ContentBlocks for Sitefinity, WP, or MailChimp (which isn't even a CMS add-on, just their name for the element types you can add to newsletters)... so that would not cause an equal amount of confusion. 

Other tools that do similar things for WordPress are called Advanced Custom Fields (/Pro), Divi, VisualComposer and there's [so many more that they have to start making top 10 lists](https://athemes.com/collections/drag-drop-page-builders-wordpress/), so it's not like ContentBlocks is the only suitable name for a tool like this. ;)

Something like "ContentElements" might be a good name as well, as (if I saw it correctly in the video) you manage the types of content that are available through the elements section, and I don't immediately see any other extras for MODX or Evo with that name.

**Comment by muzzwood** [comment]
+1 for EvoBlocks. I agree that calling it Content Blocks would create confusion.

**Comment by mnoskov** [comment]
How about CustomBlocks?

**Comment by fourroses666** [comment]
My personal thoughts are listed here, but its your decision :)

1. PageBuilder
2. LayoutBlocks
3. CustomBlocks

**Comment by pmfx** [comment]
Two more propositions :)
**PageBlocks**
**DocBlocks**

**Comment by Mark-H** [comment]
Thanks @mnoskov, appreciate the rename.
