### ISSUE TITLE
Список конфигов которые используем 

### ISSUE THREAD

**Issue by Dmi3yy** [mnoskov/pagebuilder#4]
В целом логично задать основной список конфигов 
типа просто поле, фаил, картинка, група картинок и т д 
но на сайте не всегда нужны все, а к примеру при обновлении оно опять запишет то что нужно по логике конфигов multiTV 
поэтому я бы добавил возможность указывать какие варианты блоков использовать + в идеале это сделать с привязкой к шаблону ибо на одном сайте можно использовать в разных местах 
и нужны разные наборы конфигов

**Comment by Dmi3yy** [comment]
Самый простой способ который вижу это создать папки в конфиге 
тоесть скажем если у нас указан шаблон или список шаблонов то ищем в  папке: 
config/templates/16/
config/templates/14/

если для доков надо то 
config/docs/145/

если же нет такой папки то берем стандартный набор конфигов

**Comment by mnoskov** [comment]
Мне кажется, привязка конфигов к шаблонам должна быть в настройках плагина.

**Comment by mnoskov** [comment]
В решении с папками есть существенный минус - если привязывать к нескольким шаблонам, то в случае изменений нужно будет менять в каждой папке.

**Comment by Dmi3yy** [comment]
Тут надо думать как удобней  просто в конфиге нет мульти полей 

а писать типа 
16:images,richtext.   не совсем удобно 
+ на разных шаблонах может быть одинаковый ввод данных но разный вывод

**Comment by Dmi3yy** [comment]
можно папки называть 16-18-20 )

**Comment by mnoskov** [comment]
Лучше наверное в самих конфигах добавить возможность указания шаблонов.
Что нибудь типа:
```
return [
	'title' => 'Content',
	'availablein' => [ 12, 14, 17 ],
	'fields' => ...
]
```

**Comment by Dmi3yy** [comment]
Можно пару параметров: 
hide/show in docs/templates 
и тогда да не нужно городить ничего с папками.
