### ISSUE TITLE
Sortorder of configs on the dropdown select

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#41]
Is it possible to give it a sort order?
_Maybe by ID number?_

![sortorder](https://user-images.githubusercontent.com/523389/29766955-e55f1e92-8be0-11e7-84ee-da8e38b2a6e0.png)

**Comment by mnoskov** [comment]
Maybe just alphabetical?

**Comment by fourroses666** [comment]
Yes thats the way it orders now: 
The config files are called like this and the "f" from "four" comes before the "o" from "one"
```
image-four.php
image-one.php
image-three.php
image-two.php
text-one.php
text-two.php
```

But if you know a way to be able to re-order the dropdown items that would be great.
I was thinking of adding an ID to the the config file and be able to order with that. (ASC / DESC).

Renaming the config file with 1-name.php / 2-name.php will give issues when changing it afterwards. (losing existing content)

**Comment by fourroses666** [comment]
Hi MNoskov, I have set the order like `'order' => 1,`
But it doesn't seem to work. Does it work with you?

**Comment by mnoskov** [comment]
It works only on v1.1, "issue-38" branch

**Comment by fourroses666** [comment]
Oke 👍
