### ISSUE TITLE
Looks like it doesn't work in 1.4.0b

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#47]
Just wanted to do some new demosite with PageBuilder and installed newest (development) version of Evo. (1.4.0b)

I can't select any blocks. I don't think I've done something wrong.

![pb](https://user-images.githubusercontent.com/523389/32281372-ed54192e-bf1e-11e7-917b-b84773d4b010.png)

**Comment by mnoskov** [comment]
Just tested, all fine.
Can you show your config?

**Comment by mnoskov** [comment]
I fixed sql queries on install, you can try to update and test.

**Comment by fourroses666** [comment]
Maybe the install didn't go good. 
The one in Extras is old I think (not sure, it says 0.6 but maybe its the new one).
Installed Package Manager and there it went wrong maybe.
Need to have another look and install.

I use the same settings as for an other pagebuilder site.

config/banner.php

```
<?php

return [
    'title' => 'Banner',

    //        'show_in_templates' => [ 3 ],
    //        'show_in_docs' => [ 2 ],
    //        'hide_in_docs' => [ 10, 63 ],
    
    'templates' => [
        'owner' => '@CHUNK cb-banner',
        'images' => '@CHUNK cb-banner-images'
    ],
    
    'fields' => [
        'text' => [
            'caption' => 'E-mailadres',
            'type'    => 'text',
        ],

        'images' => [
            'caption' => 'Afbeeldingen',
            'type'    => 'group',
            'fields'  => [
                'bannerkop' => [
                    'caption' => 'Kop',
                    'type'    => 'text'   
                ],
                'image' => [
                    'caption' => 'Afbeelding',
                    'type'    => 'image'   
                ],
            ],
        ],
    ],
];
```

**Comment by mnoskov** [comment]
This config works fine.

**Comment by fourroses666** [comment]
I really have no idea whats wrong. I did a PB latest version install, checked if it really was updated. Used some sample configs and tried dropdown/images/icons but nothing works.

**Comment by fourroses666** [comment]
Maybe its because of the database collation?

Everything is MyISAM | latin1_swedish_ci
The evo_pagebuilder table is InnoDB | utf8-general

**Comment by mnoskov** [comment]
Can you send access to nm@perm-tools.ru?

**Comment by fourroses666** [comment]
I have send access.

I think the problem is the database table?
When I install from Extras (probably older version) then the table is installed.
But when I install the latest version with Package Manager (and upload in /assets/packages) then installing doesn't make the evo_packagemanager table.

And probably you have done some differences in the table?

**Comment by mnoskov** [comment]
I think, it's not db problem.
But you can try to change engine and codepage manually, or delete table and execute sql-queries from install/setup.data.sql

**Comment by fourroses666** [comment]
Its not the myisam utf8 issue indeed, when looking at an other install which has the same works.
I don't know how to execute the sql actually, did an import but thats not oke. not evo_ but {PREFIX} I will do a new Evo and PD install and see if it will work.

**Comment by mnoskov** [comment]
Also check php version

**Comment by fourroses666** [comment]
PHP-: 5.5.38 (have an other site on that same server which works)

**Comment by mnoskov** [comment]
Try 5.6

**Comment by fourroses666** [comment]
I can't change the PHP version.

Probably the issue is installing PageBuilder.

I think the one from Extras is an old one.
When I try to install PB with Package Manager (is an Extra) then no database table is added.

**Comment by mnoskov** [comment]
No, problem in php version, plugin requires php 5.6.
Plugin in extras is the last and actual. Just version label incorrect.

**Comment by fourroses666** [comment]
Oke, will try on an other server with higher PHP version.

**Comment by fourroses666** [comment]
There it works! That explains it. This server has PHP 7

Its a high version thow :( 
I think I have allot sites which have < PHP 5.6

**Comment by fourroses666** [comment]
Maybe you can add it to the russian readme PHP 5.6 >

EDIT  Ah you already did :X

_and (if its not already explained) maybe add instructions to rename the /assets/plugins/pagebuilder/config/ .sample files to show the tab._

**Comment by mnoskov** [comment]
Yes, I already added
