### ISSUE TITLE
Is it possible to move TVs to the Page Builder tab?

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#48]
`mm_moveFieldsToTab('description', 'pagebuilder');`

and another question; is it possible to order the tab? 

I use mm_rules allot (like example here below, I put that as last line which results in last tab) and wonder if I can do the sortorder for the pagebuilder tab too.
`mm_createTab('SEO', 'seo', '', '', '', '100%');`

Its now random placed when I refresh the page.
![random](https://user-images.githubusercontent.com/523389/32663697-33bdfdfa-c62f-11e7-8758-a30b591ccf9c.jpg)

**Comment by mnoskov** [comment]
Yes, I have seen this too, and don't know, why this happens. Now it's not compatible. Need to test.

**Comment by fourroses666** [comment]
Looks a bit like the same when in the resource tree 2 resources/pages have the same menuindex.

**Comment by mnoskov** [comment]
Can you test this?
```
mm_moveFieldsToTab('description', 'PB_default');
```
Also, after this fix I can't reproduce tabs order bug.

**Comment by fourroses666** [comment]
Hmm, I can move TVs to the tab, that works.
Is there a way to order the (description) TV? I like to place it above the blocks.

The PB tab is now always first after the general tabs on my testsite. 
Thats better as the jumping arround thow.
(1x I had an other tab before it but maybe it was cache.)

![pb](https://user-images.githubusercontent.com/523389/32770208-0ad92ade-c91f-11e7-8370-a810701384d2.jpg)

This below creates another / new tab and the blocks are not in that one:
```
mm_createTab('Page Builder', 'PB_default', '', '', '', '100%');
mm_moveFieldsToTab('description','PB_default');
```

**Comment by mnoskov** [comment]
There's no way to sort tabs or fields.

**Comment by fourroses666** [comment]
Oke, not a real big issue :)
