### ISSUE TITLE
Q: Using Chunk outside the Snippet

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#49]
Hi Mnoskov, 

Can you help me out?
When using a block (called slider) I'd like to show the js/css links on the bottom of the page outside the Snippetcall. _(as example but could be used for different options)_

Is it possible with the tplSet?
https://github.com/mnoskov/pagebuilder/issues/31#issuecomment-316938562

I did a test but I don't know how it works. I need to add a custom Snippet?
I thought it would work something like below;

```
...
<body>
<div class="wrapper">
[[PageBuilder]]
</div>

[[PageBuilder? &tplSet=`script`]]
</body>
</html>
```

Then the slider config has:

```
        'templates' => [
            'owner' => '
                <div class="slider-item">
                    <img src="[[phpthumb? &input=`[+image+]` &options=`w=680`]]" alt="" />
                </div>
            ',
            'script' => [
                'owner' => 'Loading a chunk here with the script visible on the bottom of the page',
            ],
        ],
```

**Comment by mnoskov** [comment]
Yes, this should work, but parameter is `&templates`, not `&tplSet`
Description here - https://github.com/mnoskov/pagebuilder/blob/master/README.en.md#templates-groups

**Comment by fourroses666** [comment]
Ah sorry, it works :))
