### ISSUE TITLE
Tinymcemini issue

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#57]
I have a site where I use tinymcemini and it doesn't save edited content.
Maybe you want to have a look?

**Comment by mnoskov** [comment]
Yes, I can. Do you know my email?

**Comment by fourroses666** [comment]
Yes found it, I have mailed you the login.

Resource 'English'.
Tab Productline > when change the text and save no changes are saved.

I think its a small bug in TinyMCEmini.
Used to work but its a bit buggy I guess.

**Comment by fourroses666** [comment]
Sorry, don't know why but I thought it was a PageBuilder issue. Its an multiTV / TinyMCEmini issue.
