### ISSUE TITLE
Предложение: запуск плагина только для выбранных шаблонов

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/pagebuilder#58]
Постоянно сталкиваюсь с необходимостью **загружать** плагин только для конкретного шаблона(ов). Использую схему с отдельной вкладкой. Доступ блока для конкретного шаблона не отключает загрузку самого плагина, который нужен далеко не всегда.

В самое начало текста плагина добавил проверку
```
/* fire only for certain template */

$templ = isset($templ) ? explode(',',$templ) : false;
$cur_templ = isset($_POST['template']) ? $_POST['template'] : (isset($content['template']) ? $content['template'] : $default_template);
if ($templ && !in_array($cur_templ,$templ)) return;
...
```
И в настройки секцию для ID шаблона
```
"templ": [
    {
      "label": "Template",
      "type": "text",
      "value": "",
      "default": "",
      "desc": ""
    }
  ]
```
Таким образом если указаны ID шаблонов плагин запускается только для них.

**Comment by mnoskov** [comment]
Даже если он загружается, ничего страшного ведь в этом нет? Настройки ограничений по шаблонам есть в конфигурации блоков.

**Comment by sashabeep** [comment]
@mnoskov есть проблемы с производительностью на медленном интернете, если тестировать с симуляцией не самой быстрой скорости, плюс нагрузка на браузеры присутствует

**Comment by mnoskov** [comment]
Плагин ведь исполняется на сервере. Если он определит, что блоки в текущем шаблоне не надо выводить, то и нагрузка на сеть не увеличится.

**Comment by sashabeep** [comment]
@mnoskov все равно результаты выполнения плагина и загрузка пустой вкладки без доступных блоков никуда не денутся

**Comment by mnoskov** [comment]
На какой версии появляется пустая вкладка?

**Comment by sashabeep** [comment]
@mnoskov внезапно перепутал, на 1.2.2 нет пустой вкладки и без моей проверки
