### ISSUE TITLE
Затирание значений ТВ-параметров (контейнеров PB)

### ISSUE THREAD

**Issue by Aharito** [mnoskov/pagebuilder#67]
### Затирание значений ТВ-параметров (контейнеров PB)
1) Создаем **два** PageBuilder-контейнера: **adv_3** и **adv_4** (рекламный блок 3 и 4) с параметром `'placement' => 'tv'` в конфигурации. Пример конф-ции:
```
<?php
    return [
        'title' => '3-й Блок',
        'placement' => 'tv',        
        'templates' => [
            'owner' => '
                <div class="adv-3">
                    [+wrap+]
                </div>
            ',
        ],
    ];
```
2) Для шаблона создаём соответствующие ТВ-параметры **adv_3** и **adv_4** в MODx-категории PageBuilder.
![image](https://user-images.githubusercontent.com/6253807/37861537-6b00c0b0-2f6e-11e8-9c1a-9b939052f497.png)
3) В Конфигурации MODx включаем "Группировать ТВ на новых вкладках".
![image](https://user-images.githubusercontent.com/6253807/37861554-ab90f6d6-2f6e-11e8-829e-ff3f7d46591c.png)
4) Видим эти ТВ (контейнеры PageBuilder) при редактировании ресурса, но кнопки добавления и экспорта/импорта **дублируются** (баг №1).
![image](https://user-images.githubusercontent.com/6253807/37861589-485b9822-2f6f-11e8-9673-e4945a59d80d.png)
5) Заполняем ТВ.
![image](https://user-images.githubusercontent.com/6253807/37861608-c902c0e0-2f6f-11e8-8212-592fd89dacc5.png)
6) Нажимаем Сохранить, и в результате значение 1-го ТВ **затирается** вторым (баг №2).
![image](https://user-images.githubusercontent.com/6253807/37861629-4248864c-2f70-11e8-9d1a-783eadfcd2fb.png)

**Comment by mnoskov** [comment]
Проверьте, должно работать

**Comment by Aharito** [comment]
Проверил на всех возможных режимах группировки ТВ - всё работает. Благодарю за быстрый профессиональный отклик.
