### ISSUE TITLE
Отображение вместо ТВ

### ISSUE THREAD

**Issue by 0test** [mnoskov/pagebuilder#70]
Добрый день. Делаю по [примеру ](http://docs.evo.im/04_extras/pagebuilder/example_of_creating_containers.html) .
Хочется отображать pageBuilder вместо поля ТВ и больше нигде.
Результат получаю, но при этом на всех страницах админки виден в самом низу после контента ещё один интерфейс pageBulid'ера.  При этом show_in_templates указан нужный.

**Comment by mnoskov** [comment]
Блоки привязаны только к tv-контейнеру?
Можете показать все конфиги?

**Comment by 0test** [comment]
container.page_body.php

`<?php
return [
    'title' => 'Тело страницы',
    'addType' => 'dropdown',
    'show_in_templates' => [30],
	'order' => 1,
    'placement' => 'tv',
    'templates' => [
        'owner' => '
            <div class="body">
                [+wrap+]
            </div>
        ',	
    ],
];`

Также 2 файла для блоков, но там ничего такого, копи-паст.
В плагине в параметрах всяко разно игрался с placement. Сейчас вставил туда tv, иначе сделать не выходило, чтобы он вместо твшки показал.

**Comment by mnoskov** [comment]
Ну вобще настройки плагина это как контейнер с именем 'default'. И он никогда не тестировался для работы вместо tv. Этот контейнер будет показываться всегда, пока к нему привязан хоть один блок, либо в отдельной вкладке, либо под контентом.

И если в конфиге блоков не указана привязка к какому-либо контейнеру, блок автоматически привязывается к контейнеру 'default'

Покажите конфиги блоков.

**Comment by 0test** [comment]
`<?php

    return [
        'title' => 'Текстовый блок',        
        'image' => 'assets/plugins/pagebuilder/images/text.jpg',
        'container' => 'page_body',
        'templates' => [
            'owner' => '
				<div class="common-content">
					<h2 class="gray-wrapper">[+head+]</h2>
					[+richtext+]
                </div>
            ',
        ],
        'fields' => [
			'head' => [
                'caption' => 'Заголовок',
                'type'    => 'text',
			],
            'richtext' => [
                'caption' => 'Текст',
                'type'    => 'richtext',
                'default' => '',
                'options' => [
                    'height' => '300px',
                ],
            ],
			
        ]	
    ];

`

**Comment by mnoskov** [comment]
Других нет?

**Comment by mnoskov** [comment]
Затестил ваш конфиг, он рабочий. Единственно, настройка 'show_in_templates' не нужна, т.к. в данном случае область видимости определяется настройками tv-параметра.

**Comment by 0test** [comment]
![- -1](https://user-images.githubusercontent.com/10080727/38987302-ddf2d626-43d7-11e8-9f62-004400b76ea0.png)
Ну конфиги рабочие, да.
Вопрос как избавиться от этого вот снизу)

**Comment by mnoskov** [comment]
Рабочие - значит работают так как нужно, без вот таких артефактов. Видимо в чем-то все-таки есть отличие между нашими конфигурациями. TV в настройках плагина уберите, проверьте привязку остальных блоков.

**Comment by 0test** [comment]
Ставлю Placement = tab, получаю вкладку везде. Игнорится show_in_templates. Ставлю content, получаю вкладку в контенте.

**Comment by mnoskov** [comment]
Проверьте привязку остальных блоков.
