### ISSUE TITLE
PageBuilder doesn't shows up if page is unpublished

### ISSUE THREAD

**Issue by pmfx** [mnoskov/pagebuilder#77]
PageBuilder doesn't shows up if page is unpublished. This makes "Preview" of unpublished resource not usable as the content is not visible.

**Comment by mnoskov** [comment]
https://github.com/mnoskov/pagebuilder/commit/14129cb9c96501158ebe77633811fd778be822e9

**Comment by pmfx** [comment]
Perfect. Thanks for quick fix!
