### ISSUE TITLE
Есть ли пример использования [+{имя_поля}_index+] и [+{имя_поля}_iteration+], а то они что-то не работают..

### ISSUE THREAD

**Issue by EGO7000** [mnoskov/pagebuilder#79]
Приветствую!
Можно ли увидеть рабочий пример конфига с использованием [+{имя_поля}_index+] и [+{имя_поля}_iteration+] для групповых параметров? А то как только не пробовал их выводить - тишина в ответ... Уже подумал, может быть они вовсе не работают?
Спасибо!

**Comment by mnoskov** [comment]
```php
return [
    'title' => 'test',

    'templates' => [
        'owner' => '[+items+]',
        'items' => '[+items_index+], [+items_iteration+]<br>',
    ],

    'fields' => [
        'items' => [
            'type' => 'group',
            'fields' => [
                'title' => [
                    'caption' => 'test',
                    'type' => 'text',
                ],
            ],
        ],
    ],
];
```

**Comment by EGO7000** [comment]
Спасибо большое - всё работает! Видимо недосып, т.к. подумал из документации, что в имени поля нужно указывать имя конкретного поля из группы, а не имя самой группы! В примерах нигде не нашёл, было бы здорово внести в документацию на docs.evo.im или хотя бы в примерах для таких недоспавших как я)))
Ещё раз спасибо за быстрый ответ и отличный компонент!

**Comment by modx-lab** [comment]
нужно добавить в документацию уточнение, путает ))
