### ISSUE TITLE
Multiple templates

### ISSUE THREAD

**Issue by Sybrenb** [mnoskov/pagebuilder#84]
Hi all,

I'm using pagebuilder and it works great!

I only have one problem.. I want to use multiple template chuncks for one block. I now have:

```
'templates' => [
'owner' => '@CHUNK pb-t',
'kolom' => '@CHUNK pb-k',
'content' => '@CHUNK pb-chunk',
],
```

But I want the 'content' block to use in multiple templates at the same page, I've tried:

```
'templates' => [
'owner' => '@CHUNK pb-t',
'kolom' => '@CHUNK pb-k',
'content' => '@CHUNK pb-chunk',
'content' => '@CHUNK pb-chunk2',
],
```

But it doesn't work.. Can somebody please help me? It would be great to use the same block in multiple template chunks.. :) :)

**Comment by mnoskov** [comment]
Can you show full config?

**Comment by Sybrenb** [comment]
`<?php
return [
'title' => 'Formulier',
'show_in_templates' => [ 6 ],
'order' => 1,

'templates' => [
'owner' => '@CHUNK pb-t',
'kolom' => '@CHUNK pb-k',
'content' => '@CHUNK pb-chunk',	

],

'fields' => [
'to' => [
'caption' => 'to',
'type'    => 'text',
],

'bcc' => [
'caption' => 'bcc',
'type'    => 'text',
],

'from' => [
'caption' => 'from',
'type'    => 'text',
],

'fromname' => [
'caption' => 'fromname',
'type'    => 'text',
],

'onderwerp' => [
'caption' => 'onderwerp',
'type'    => 'text',
],


'buttons1' => [
'caption' => 'Input velden',
'type'    => 'group',
'fields'  => [

'btn-id' => [
'caption'  => 'ID veld (1 woord)',
'type'     => 'text',
'layout'   => 'horizontal',
],
	
'btn-naam' => [
'caption'  => 'Naam veld',
'type'     => 'text',
'layout'   => 'horizontal',
],
	

'verplicht' => [
'caption'  => 'Verplicht?',
'type'     => 'radio',
'default'  => 'ghost',
'layout'   => 'horizontal',
'elements' => [
	'ja' => 'Ja',
	'nee'   => 'Nee',

],
],
],
],		
],
];`

**Comment by mnoskov** [comment]
Can't see `content` field in fields list

**Comment by Sybrenb** [comment]
I want to get the input values from 'content' =>
 in multiple 
=> '@chunk pb-chunk',

Like:
'content' => '@chunk pb-chunk',
'content' => '@chunk pb-chunk2',

but this doesnt work.. 

Also this doesnt work: 'content' => '@chunk pb-chunk, @chunk pb-chunk2',

**Comment by Sybrenb** [comment]
I want to use the fields I enter here in multiple call chunks

`'from' => [
'caption' => 'from',
'type' => 'text',
],`

**Comment by mnoskov** [comment]
Sorry, I don't understand what you want to do. Maybe it is templates groups - http://docs.evo.im/en/04_extras/pagebuilder/templates-2.html

**Comment by Sybrenb** [comment]
I have this:

```
'inmail2' => '@CHUNK pb-required',


'inmail2' => [
'caption' => 'Verplicht',
'type'    => 'group',
'fields'  => [

'inmailid' => [
'caption'  => 'ID',
'type'     => 'text',
'layout'   => 'horizontal',
],


'inmailmelding' => [
'caption'  => 'Melding',
'type'     => 'text',
'layout'   => 'horizontal',
],
'type' => [
'caption'  => 'Type veld',
'type'     => 'radio',
'default'  => 'ghost',
'layout'   => 'horizontal',
'elements' => [
'tekst' => 'Tekst',
'radio'   => 'Keuzeveld',
'checkbox'   => 'Keuzeveld meerdere antwoorden',	



],
],
],
],
```


But I want to use 'inmail2' in multiple different chunks.

this obviously don't work:
```
'inmail2' => '@CHUNK pb-required',
'inmail2' => '@CHUNK other-chunk',
```

**Comment by fourroses666** [comment]
I think I have the same issue. I want to build Tabs `type: group`.

But [+items+] need to be split somehow.

        'templates' => [
            'owner' => '@CHUNK cb_tabs',
            'items' => '@CHUNK cb_tabs-row',
        ],
	
	'fields' => [
            'items' => [
                'caption' => 'Tab',
                'type'    => 'group',
                'fields'  => [
			'tab-name' => [
				'caption' => 'Tabname',
				'type'    => 'text',
			],
			'text' => [
				'caption' => 'Text',
				'type'    => 'textarea',
			],
                ],
            ],
        ],

Chunk `cb_tabs-row` will output like this:
```
<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab"><label for="tab[+items_iteration+]">[+tab-name+]</label>
<div class="tab-content">[+text+]</div>
--
<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab"><label for="tab[+items_iteration+]">[+tab-name+]</label>
<div class="tab-content">[+text+]</div>
```

But I need:
```
<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab"><label for="tab[+items_iteration+]">[+tab-name+]</label>
<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab"><label for="tab[+items_iteration+]">[+tab-name+]</label>
--
<div class="tab-content">[+text+]</div>
<div class="tab-content">[+text+]</div>
```

Don't know if there is a solution for this. Would like to seperate these rows but on back-end it needs to be one item (tab-name and text as one added item).

**Comment by fourroses666** [comment]
I have it working;

		'templates' => [
			'owner' => '@CHUNK cb_tabs',
			'items' => [
				'title' => '<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab" checked><label for="tab[+items_iteration+]">[+tab+]</label>',
				'text' => '<div class="tab-content">[+text+]</div>',
			],
		],
		
		'fields' => [
			'kop' => [
				'caption' => 'Kop',
				'type'    => 'text',
			],
			'items' => [
				'caption' => 'Tab',
				'type'    => 'group',
				'fields'  => [
					'tab' => [
						'caption' => 'Tab kop',
						'type'    => 'text',
					],
					'text' => [
						'caption' => 'Tekst',
						'type'    => 'richtext',
					],
				],
			],
		],

Chunk cb_tabs;

```
<section class="cb_tabs">
	<div class="container">
		<div class="row">
			<h2>[+kop+]</h2>
			
			<div class="tab-wrap">
				[+items.title+]
				[+items.text+]
			</div>

		</div>
	</div>
</section>
```

**Comment by Sybrenb** [comment]
This is great, but I need to have something like:

`'templates' => [
		'owner' => '@CHUNK cb_tabs',
		'items' => [
			'title' => '<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab" checked><label for="tab[+items_iteration+]">[+tab+]</label>',
			'text' => '<div class="tab-content">[+text+]</div>',
		],
	'itemsextra' => [
			'title2' => '<input type="radio" id="tab[+items_iteration+]" name="tabs" class="tab" checked><label for="tab[+items_iteration+]">[+tab+]</label>',
			'text2' => '<div class="tab-content">[+text+]</div>',
		],
	],`


But this doesn't seem work.. :(

**Comment by Sybrenb** [comment]
This is great, but I can't rename 'items' with, for example, items2. It only seems to work with items. Is it possible to use multiple of these item elements with another name?

**Comment by mnoskov** [comment]
This is the name of templates set.
