### ISSUE TITLE
Add blank item info text

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#87]
Would be nice to have the option to add a block which is blank on back-end, just some info text.
If I'm not mistaken this isn't possible.

        'fields' => [
            'blank' => [
                'caption' => '<i>This is a seperator, you don't need to do anything else!</i>',
                'type'    => 'info',
                ],
            ],
        ],

**Comment by Sybrenb** [comment]
Without (extra) caption, but the block name is still clear for the user (Google Maps blok).

<?php
return [
'title' => 'Google maps blok',
'show_in_templates' => [ 3 ],
'order' => 1,

'templates' => [
'owner' => '@CHUNK pb-maps',
],

'fields' => [

],
];

**Comment by Sybrenb** [comment]
Without (extra) caption, but the block name is still clear for the user (Google Maps blok).


return [
'title' => 'Google maps blok',
'show_in_templates' => [ 3 ],
'order' => 1,

'templates' => [
'owner' => '@CHUNK pb-maps',
],

'fields' => [


],
];

**Comment by fourroses666** [comment]
That would work but I rather have some information option(s) to add text on the back-end
