### ISSUE TITLE
Anchors required for all when you set one

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#88]
Is it correct when you set one anchor on a template its required to add an empty anchor to all other templates? 

I get the message: `Templates set 'anchors' not defined` for every template which has no anchor set. So I need to add the anchor with an empty chunk.

        'templates' => [
            'owner' => '@CHUNK cb_heading',
			
			'anchors' => [
				'owner' => '@CHUNK cb_nothing',
			],
        ],

**Comment by mnoskov** [comment]
Yes, must add empty
