### ISSUE TITLE
Решетка Grid для вставки блоков.

### ISSUE THREAD

**Issue by dmpol18** [mnoskov/pagebuilder#93]
Здравствуйте! 
Интересует заполнение Pagebuiler не сразу модулями (1 ряд - 1 модуль), 
а сначала создать решетку (вставляем ряд, количество и размер колонок), 
а уже в каждую колонку - блок PageBuilder. 
В общем как это сделано в большинстве PageBuilder модулей на Wordpress.

Хотелось бы узнать и обсудить готовы ли доработать данный модуль в этом направлении.
Плюс есть еще несколько доработок.
Пожалуйста, напишите мне на почту dmpol18@ukr.net или в телеграме dmpol18

**Comment by mnoskov** [comment]
Это планируется к реализации

**Comment by dmpol18** [comment]
А каковы примерные сроки по данной возможности?

Еще интересует возможность предпросмотра или в идеале, что возможно даже проще, редактрования прямо на фронте (панель ряда/блоков, ниже сразу добавляются соответствующие элементы).

**Comment by dmpol18** [comment]
Заказчику нужен данный функционал, можем предложить ему платную доработку, чтобы ускорить процесс.
Можете оценить часы сколько Вам нужно на данные работы, чтобы мы обсудили с Вами и заказчиком возможную платную работу по этому вопросу?

**Comment by mnoskov** [comment]
https://t.me/mnoskov
