### ISSUE TITLE
Prepare. Block ID

### ISSUE THREAD

**Issue by dmpol18** [mnoskov/pagebuilder#94]
Идет 2 одинаковых блока подряд с разными настройками.
Необходимо для запуска скриптов использовать ID блока (определить блок как уникальный).
В админке вижу у блока 
`<input type="hidden" name="contentblocks_id" value="279">` 
Но в config файле, функции prepare, к переменной ID блока не смог найти доступ.

**Comment by mnoskov** [comment]
Да, его вроде как не достать. Можно использовать итерацию
