### ISSUE TITLE
TinyMCE mini

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#96]
What file does PageBuilder use for richtext mini?

I'd like to change it but can't find the theme. /assets/plugins/tinymce4/theme/
Would expect to use: theme.tinymce4.mini.inc.php but it doesn't.

```
	'type'    => 'richtext',
	'theme'   => 'mini',
	'options' => [
		'height' => '80px',
		],
```

**Comment by mnoskov** [comment]
https://github.com/evolution-cms/evolution/blob/1.4.x/assets/plugins/tinymce4/theme/theme.tinymce4.mini.inc.php

**Comment by fourroses666** [comment]
Yes, its not using the that config. I have looked at TinyMCE settings and Configuration > Interface > TinyMCE4 > Theme settings etc. I use the latest PB from Extras.

<img width="753" alt="mini" src="https://user-images.githubusercontent.com/523389/108756738-39570a00-7549-11eb-9551-6bc11d6fb28a.png">

<img width="777" alt="pb" src="https://user-images.githubusercontent.com/523389/108756741-3a883700-7549-11eb-98a3-5641455bceb6.png">

**Comment by fourroses666** [comment]
I'm on EVO 2.0.4, did notice on an 1.4.12 version it does work. I will try to use an older version of PB and look if a new "issue"

**Comment by fourroses666** [comment]
I will use this, can't get it modified.
	'type'    => 'richtext',
(no theme)
	'options' => [
		'height' => '100px',

**Comment by fourroses666** [comment]
Don't know if there was a fix but it seems to works now, 
I made a copy of ../tinymce4/theme/theme.tinymce4.mini.inc.php and did some changes.

In pagebuilder config I call it by:
```
'richtext' => [
                'caption' => 'Text',
                'type'    => 'richtext',
		'default' => '',
                'theme'   => 'mini2',
                'options' => [
                    'height' => '200px',
                ],
            ],
```
