### ISSUE TITLE
Install from Extras in EVO 3 databasetable no prefix.

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/pagebuilder#99]
Installing PageBuilder by Extras on EVO 3.1.2 worked but the table had no prefix. After manual adding it worked.

**Comment by fourroses666** [comment]
Seems there is a databasetale but no "preset" . like evo_pagebuilder but pagebuilder.
Anyway seems TinyMCE still doesn't work for pages with PB in tab

**Comment by mnoskov** [comment]
https://github.com/evolution-cms/evolution/pull/1920
